### ISSUE TITLE
你好，怎么在本地环境安装一个lvygpt？

### ISSUE THREAD

**Issue by qiaoyafeng** [WangRongsheng/ChangChunTeng#1]
我想在本地安装一个lvygpt，安装文档有没有，还有数据模型在哪里可以找到？

**Comment by WangRongsheng** [comment]
现在您可以体验开源版本的IvyGPT：https://huggingface.co/spaces/wangrongsheng/IvyGPT

**Comment by qiaoyafeng** [comment]
你好，我已经体验过lvygpt了，很好，如果想在服务器部署一个开源版的lvygpt服务，应该在哪里找到源码，还有安装文档在哪里可以找到？
